---
version: 2
title: Create, read and delete replication controller with random name
subtasks:
- title: Run a single workload with create/read/delete replication controller
  scenario:
    Kubernetes.create_delete_replication_controller:
      replicas: 3
      image: kubernetes/pause
  runner:
    constant:
      concurrency: 2
      times: 10
  contexts:
    namespaces:
      count: 4
      with_serviceaccount: true
- title: Run create/read/delete replication controller with rps runner
  scenario:
    Kubernetes.create_delete_replication_controller:
      replicas: 3
      image: kubernetes/pause
  runner:
    rps:
      rps: 2
      times: 10
  contexts:
    namespaces:
      count: 4
      with_serviceaccount: true
