---
  Kubernetes.run_namespaced_pod:
  -
    args:
      image: kubernetes/pause
      sleep_time: 1
      retries_total: 30
    runner:
      type: rps
      times: 6
      rps: 3
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
    sla:
      failure_rate:
        max: 0
  -
    args:
      image: kubernetes/pause
      sleep_time: 1
      retries_total: 30
    runner:
      type: constant
      times: 4
      concurrency: 4
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
    sla:
      failure_rate:
        max: 0