---
  Kubernetes.scale_replication_controller:
  -
    args:
      image: kubernetes/pause
      replicas: 1
      scale_replicas: 3
      sleep_time: 1
      retries_total: 50
    runner:
      type: constant
      times: 4
      concurrency: 4
    context:
      kubernetes.namespaces:
        count: 4
        with_serviceaccount: yes
    sla:
      failure_rate:
        max: 0