---
version: 2
title: Create, read, scale and delete replication controller with random name
subtasks:
- title: Run a single workload with create/read/scale/delete replication controller
  scenario:
    Kubernetes.scale_replication_controller:
      replicas: 1
      scale_replicas: 3
      image: kubernetes/pause
      sleep_time: 1
      retries_total: 50
  runner:
    constant:
      concurrency: 2
      times: 10
  contexts:
    namespaces:
      count: 4
      with_serviceaccount: true
- title: Run create/read/scale/delete replication controller with rps runner
  scenario:
    Kubernetes.scale_replication_controller:
      replicas: 1
      scale_replicas: 3
      image: kubernetes/pause
      sleep_time: 1
      retries_total: 50
  runner:
    rps:
      rps: 2
      times: 10
  contexts:
    namespaces:
      count: 4
      with_serviceaccount: true
